// Marketing copy for BuggedOut, generated by the content workflow.
// Home-page sections + per-route SEO/header copy. Edit freely.

export interface RouteCopy {
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  sub: string;
}

export const ROUTES: Record<"home" | "games" | "gallery" | "contact", RouteCopy> =
  {
  "home": {
    "title": "BuggedOut.com — The Live Animal Racing Arena",
    "description": "Real animals, live races, pure chaos. Chickens, crabs, fish and roaches go head-to-head in real time. No replays, no scripts, no two rounds alike.",
    "eyebrow": "Live Animal Racing",
    "h1": "Race. Cheer. Repeat.",
    "sub": "Real animals. Real races. Real chaos."
  },
  "games": {
    "title": "The Lineup — Live Games & Roulette | BuggedOut.com",
    "description": "Browse the full lineup of live animal races and roulette. Meet the chickens, fish, crabs and roaches, see how each game runs, and watch the chaos unfold.",
    "eyebrow": "The Lineup",
    "h1": "Meet The Runners",
    "sub": "Every game runs live. Meet the contestants and watch it all go sideways."
  },
  "gallery": {
    "title": "Inside the Pit — Arena Gallery | BuggedOut.com",
    "description": "Get close to the action. Neon-lit shots of the animal athletes, the lanes and the HUD from inside BuggedOut's live arena.",
    "eyebrow": "Inside the Pit",
    "h1": "The Arena, Up Close",
    "sub": "Neon, lanes and live critters. Welcome to the floor."
  },
  "contact": {
    "title": "Contact the Crew — BuggedOut.com",
    "description": "Questions about the arena, the games or partnerships? Reach the BuggedOut crew trackside. Fast answers, straight talk, no runaround.",
    "eyebrow": "Trackside Support",
    "h1": "Talk to the Crew",
    "sub": "Stuck, curious, or want in? Drop us a line."
  }
};

export const HOME = {
  "heroEyebrow": "THE LIVE ANIMAL ARENA",
  "heroTitleLines": [
    "Eight animals.",
    "All chaos.",
    "BUGGEDOUT."
  ],
  "heroSubhead": "Live animal races where the contestants have no idea they're competing.",
  "why": [
    {
      "h": "Always Live",
      "p": "Every round runs in real time, so the chaos you watch is the real thing, start to finish."
    },
    {
      "h": "Truly Random",
      "p": "No loops, no replays, no trained tricks; the animals do whatever they feel like."
    },
    {
      "h": "Instant Results",
      "p": "Every round settles in seconds, locked in before the next rooster even wakes up."
    }
  ],
  "lineup": [
    {
      "name": "Rooster",
      "trait": "Struts first, thinks never."
    },
    {
      "name": "Hen",
      "trait": "Pecks a path only she understands."
    },
    {
      "name": "Rabbit",
      "trait": "Gone before the gate finishes opening."
    },
    {
      "name": "Frog",
      "trait": "One jump can flip the whole round."
    },
    {
      "name": "Beetle",
      "trait": "Slow, stubborn, weirdly hard to read."
    },
    {
      "name": "Crab",
      "trait": "Runs sideways, wins sideways, leaves sideways."
    },
    {
      "name": "Fish",
      "trait": "Swims like the lane owes it money."
    },
    {
      "name": "Duck",
      "trait": "Calm up top, scheming underneath."
    }
  ],
  "winner": {
    "eyebrow": "ROUND SETTLED",
    "h": "We Have A Winner.",
    "p": "When the winner crosses first, the arena floods gold and the whole floor erupts. Screenshot it quick; the next round is already loading."
  },
  "howItWorks": [
    {
      "h": "Pick Your Game",
      "p": "Eight ways to play, from Chicken Shit Bingo to Tunnel Vision, each with its own brand of mayhem."
    },
    {
      "h": "Meet The Runners",
      "p": "Get to know the contestants before the gate opens, every one a wildcard with no clue it's competing."
    },
    {
      "h": "Watch It Live",
      "p": "The floor lights up and the animals improvise everything, because nobody told them the plan."
    },
    {
      "h": "See Who Wins",
      "p": "First nose past the line takes the round, then it all resets on Lane Racing, Roulette, or Three Door Monty."
    }
  ],
  "stats": [
    {
      "value": "8",
      "label": "Live games, no two alike"
    },
    {
      "value": "47,000+",
      "label": "Rounds run this week"
    },
    {
      "value": "9s",
      "label": "Average round time"
    },
    {
      "value": "24/7",
      "label": "The arena never sleeps"
    }
  ],
  "cta": {
    "h": "Sign up. Tune in. See what happens.",
    "p": "Join the list for round alerts, early access, and a front-row seat to Forked Fate, Split Decision, and The Great Escape. The animals are waiting; they just don't know it."
  }
} as const;
