// Marketing copy for BuggedOut, generated by the content workflow.
// Home-page sections + per-route SEO/header copy. Edit freely.

export interface RouteCopy {
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  sub: string;
}

export const ROUTES: Record<"home" | "games" | "gallery" | "contact", RouteCopy> =
  {
  "home": {
    "title": "BuggedOut.com — Live Animal Racing & Betting Arena",
    "description": "Real animals, live races, real stakes. Chickens, crabs, fish and roaches go head-to-head while you call the winner. No replays, no scripts. 18+.",
    "eyebrow": "Live Animal Gaming",
    "h1": "Race. Bet. Repeat.",
    "sub": "Real animals. Real races. Real chaos."
  },
  "games": {
    "title": "The Lineup — Live Games & Roulette | BuggedOut.com",
    "description": "Browse the full lineup of live animal races and roulette. Back a chicken, fish, crab or roach, lock your bet, and watch it run. 18+ only.",
    "eyebrow": "The Lineup",
    "h1": "Pick Your Runner",
    "sub": "Every game runs live. Choose your fighter and back it."
  },
  "gallery": {
    "title": "Inside the Pit — Arena Gallery | BuggedOut.com",
    "description": "Get close to the action. Neon-lit shots of the animal athletes, the lanes and the HUD from inside BuggedOut's live betting pit. 18+.",
    "eyebrow": "Inside the Pit",
    "h1": "The Arena, Up Close",
    "sub": "Neon, lanes and live critters. Welcome to the floor."
  },
  "contact": {
    "title": "Contact the Crew — BuggedOut.com",
    "description": "Questions about the arena, payouts or partnerships? Reach the BuggedOut crew trackside. Fast answers, straight talk, no runaround. 18+.",
    "eyebrow": "Trackside Support",
    "h1": "Talk to the Crew",
    "sub": "Stuck, curious, or want in? Drop us a line."
  }
};

export const HOME = {
  "heroEyebrow": "THE LIVE ANIMAL ARENA",
  "heroTitleLines": [
    "Eight animals.",
    "All chaos.",
    "BUG OUT."
  ],
  "heroSubhead": "Live prediction games where the contestants have no idea they're competing.",
  "why": [
    {
      "icon": "🟢",
      "h": "Always Live",
      "p": "Every round runs in real time, so the chaos you bet on is the exact chaos you watch."
    },
    {
      "icon": "🎲",
      "h": "Truly Random",
      "p": "No loops, no replays, no trained tricks; the animals do whatever they feel like."
    },
    {
      "icon": "💸",
      "h": "Fast Payouts",
      "p": "Call it right and your winnings land before the next rooster even wakes up."
    }
  ],
  "lineup": [
    {
      "emoji": "🐓",
      "name": "Rooster",
      "trait": "Struts first, thinks never."
    },
    {
      "emoji": "🐔",
      "name": "Hen",
      "trait": "Pecks a path only she understands."
    },
    {
      "emoji": "🐇",
      "name": "Rabbit",
      "trait": "Gone before the gate finishes opening."
    },
    {
      "emoji": "🐸",
      "name": "Frog",
      "trait": "One jump can void your whole ticket."
    },
    {
      "emoji": "🪲",
      "name": "Beetle",
      "trait": "Slow, stubborn, weirdly hard to read."
    },
    {
      "emoji": "🦀",
      "name": "Crab",
      "trait": "Bets sideways, wins sideways, leaves sideways."
    },
    {
      "emoji": "🐟",
      "name": "Fish",
      "trait": "Swims like the odds owe it money."
    },
    {
      "emoji": "🦆",
      "name": "Duck",
      "trait": "Calm up top, scheming underneath."
    }
  ],
  "winner": {
    "eyebrow": "ROUND SETTLED",
    "h": "Called It.",
    "p": "When your pick crosses first, the arena floods gold and your balance jumps before you can blink. Screenshot it quick; the next round is already loading."
  },
  "howItWorks": [
    {
      "h": "Pick Your Game",
      "p": "Eight ways to play, from Chicken Shit Bingo to Tunnel Vision, each with its own brand of mayhem."
    },
    {
      "h": "Place Your Bet",
      "p": "Lock your prediction before the gate opens, and the odds keep shifting right up to the buzzer."
    },
    {
      "h": "Watch It Live",
      "p": "The floor lights up and the animals improvise everything, because nobody told them the plan."
    },
    {
      "h": "Get Paid",
      "p": "Win, cash out on the spot, then run it back on Lane Racing, Roulette, or Three Door Monty."
    }
  ],
  "stats": [
    {
      "value": "8",
      "label": "Live games, no two alike"
    },
    {
      "value": "47,000+",
      "label": "Rounds called this week"
    },
    {
      "value": "9s",
      "label": "Average cash-out time"
    },
    {
      "value": "18+",
      "label": "Because money's on the line"
    }
  ],
  "cta": {
    "h": "Sign up. Place one bet. See what happens.",
    "p": "New players get a starter stack to test Forked Fate, Split Decision, and The Great Escape before betting big. 18+. The animals are waiting; they just don't know it."
  }
} as const;
